// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSJ6l0biRImbCka_Gow5tpkTrWmOAkmIQ',
    appId: '1:302808254672:web:450699cb1f845bd067b6d5',
    messagingSenderId: '302808254672',
    projectId: 'learningdart-flutter-ed-32',
    authDomain: 'learningdart-flutter-ed-32.firebaseapp.com',
    storageBucket: 'learningdart-flutter-ed-32.appspot.com',
    measurementId: 'G-ML5EXGPW4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtZSLDW9eLxRZwWShyoWW7DT03Q7bPV3Y',
    appId: '1:302808254672:android:4c77c5dcd911618867b6d5',
    messagingSenderId: '302808254672',
    projectId: 'learningdart-flutter-ed-32',
    storageBucket: 'learningdart-flutter-ed-32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg-SaDcfIQDJhZX1QnFq_ueQsDtU0fFIY',
    appId: '1:302808254672:ios:c8b873033454c89c67b6d5',
    messagingSenderId: '302808254672',
    projectId: 'learningdart-flutter-ed-32',
    storageBucket: 'learningdart-flutter-ed-32.appspot.com',
    iosClientId: '302808254672-d9kqrvpbtsomk799qd6npsgasc45cdf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg-SaDcfIQDJhZX1QnFq_ueQsDtU0fFIY',
    appId: '1:302808254672:ios:c8b873033454c89c67b6d5',
    messagingSenderId: '302808254672',
    projectId: 'learningdart-flutter-ed-32',
    storageBucket: 'learningdart-flutter-ed-32.appspot.com',
    iosClientId: '302808254672-d9kqrvpbtsomk799qd6npsgasc45cdf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );
}
